// Written by James Mu
// Template from Dr. Palmeri

@startuml

[*] -> init

state init {
    init_run: set up
}

state idle {
    idle_run: wait
}

state reading_adc {
    reading_adc_run: read adc
    reading_adc_run: convert adc to mV
}

state blinking {
    blinking_enter: convert mV to Hz
    blinking_enter: start timers to blink at Hz
    blinking_run: wait
}

init -> idle : init done
idle -d-> reading_adc : button press
reading_adc -> blinking : done reading adc
blinking -> idle : done blinking
blinking_enter -> blinking_run : start timers
idle -> [*] : give up lol

@enduml